FROM richarvey/nginx-php-fpm:latest

COPY . /var/www/html

ENV SKIP_COMPOSER 0
ENV PHP_ERRORS_STDERR 1
ENV RUN_SCRIPTS 1
ENV REAL_IP_HEADER 1

ENV WEBROOT /var/www/html/public
ENV APP_ENV production
ENV APP_DEBUG false

RUN composer install --no-dev --optimize-autoloader

RUN chown -R webuser:webgroup /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE 80